### ISSUE TITLE
No plotting with trials containing 2 varieties

### ISSUE THREAD

**Issue by jrhadams** [cran/SpATS#1]
I realise this repo is only a CRAN mirror, but this is the only public repository I could find for issues. 

Whenever I run any form of SpATS spatial model on a trial containing two genotypes and attempt plotting the model object, I encounter the following error: `Error in 1:ncol(geno.model.matrix) : argument of length 0`.  Modifying your example with a meaningless 2-level genotype shows this same error. 

```R
library(SpATS);library(data.table)
set.seed(3459)
data(wheatdata)
dat<- as.data.table(wheatdata)
#Get genotype and coerce necessary columns to factor
dat[,genoAlt:=sample(c('g1','g2'),.N,replace = T)
    ][,c('R','C','genoAlt'):=lapply(.(row,col,genoAlt),
                                    as.factor)]
summary(dat)
#model
m0 <- SpATS(response = "yield", spatial = ~ SAP(col, row, nseg = c(10,20), degree = 3, pord = 2), 
            genotype = "genoAlt", fixed = ~ colcode + rowcode, random = ~ R + C, data = dat, 
            control =  list(tolerance = 1e-03))
summary(m0) #Fit is fine 
plot(m0) #Fails
```
I believe the issue is that the contrast given in line 12 within your [plot.SpATS()](https://github.com/cran/SpATS/blob/d0bffb316470282ebf6308f960a1a8768add36ab/R/plot.SpATS.R#L12) should be an array rather than a vector. Adding something simple like a:

```R
  if(!is.matrix(Z_geno))
    Z_geno<- matrix(Z_geno)
```
in your [construct.genotype.prediction.matrix()](https://github.com/cran/SpATS/blob/master/R/construct.genotype.prediction.matrix.R) function is enough to resolve it, but there is likely a more eloquent way to handle this in the previous operations.

I should note that while this is clearly an edge case, doing this same exercise with genotype as a random effect plots successfully.

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!
